name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check Rust targets
        run: cargo check --locked --all-targets --all-features

      - name: Run Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --locked --all-features
